model_config:
  num_epochs : 50
  batch_size : 128
  optimizer : adam
  learning_rate : 0.001
  input_dim : 2048
  hidden_dim : 2048
  device : cuda:2
  model_name : clipRN50_vqa_v3


data_config:
  train_data_path : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/vizviz/vqa/train_df_RN50.json
  val_data_path : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/vizviz/vqa/val_df_RN50.json
  save_dir : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/runs/clip_vqa
