num_epochs : 50
batch_size : 64
optimizer : adam
learning_rate : 0.01
momentum : 0.9
device : cuda:1
model_name : blip_vqa

train_data_path : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/vizviz/vqa/train_df_RN50.json
val_data_path : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/vizviz/vqa/val_df_RN50.json
save_dir : /nfs/home/scg1143/MLDS/Quarter3/DeepLearning/Project/VQA-ObjectDetection/runs/blip_vqa
